### ISSUE TITLE
How authenticate requests to microservices?

### ISSUE THREAD

**Issue by alizamani** [PoweredLocal/vrata#11]
Hi, Thank you very much for this great api gateway! But you did't say anything about authenticating between gateway and microservices ! 
For example we have two microservice : **service1** and **service2** + **vrata as api gateway**.

I have three problems now:

1.Now we want to send request from **service1** to **service2** by **vrata**. In which one we should install **lumen-passport**? in vrata ? in two microservices? or all three? 

2.How to determine in the **vrata** that a route needs permission ? If we just do not use ```'public' => true```, is it enough?

3.Also if access to **service1** requires authentication, how to do it? 

Thanks

**Comment by ellisio** [comment]
@alizamani Just a thought there, but have you considered using the Pub/Sub pattern?

1. Service A emits a `user.registered` event.
2. Service B listeners for `user.registered` and does something.

You don't want to directly tie internal services together through internal requests, if possible, as that defeats the purpose of decoupling services. Meaning, if Service B goes down, Service A should still operate without concern.

An example of this pattern in practice is user registration in one of our applications. We request a phone number during registration, but have two services:

1. `/v1/users`
2. `/v1/phones`

The registration request calls `/v1/users/register` with the payload, including a phone number. Once the user is created on the User service we emit `user.registered` with the user data, as well as the request payload sent on the request (includes the phone number).

The Phone number service has a backend listener subscribed to the Pub/Sub and creates a phone number record within it's database for the provided user.

If the phone number service ever goes down, and a user registers within that downtime, we have decided it is okay to not store the phone number and leave registration operational. We can collect that data at a later time using in-app logic, or they will end up filling it out at some point.

**Comment by dusterio** [comment]
@alizamani traditionally in this architectural pattern, underlying services only perform authorization, no authentication - eg. what a user can do on your service, but not who the user is. so "vrata" performs the authentication by verifying the JWT token and passes its data (user ID from the token, token scopes) to all microservices when requests are made (HTTP headers - X-User, X-Token-Scopes). then your microservices can decide what permissions to give to that user. You could base your permission system on JWT token scopes or you could have some internal logic in microservices
