### ISSUE TITLE
Guzzle Dependency

### ISSUE THREAD

**Issue by djfurman** [PoweredLocal/vrata#12]
Hi!

A friend sent me a link to your [libraries.io](https://libraries.io/github/PoweredLocal/vrata) description and I'm excited to get it running. I noticed as I install that the composer dependency is behind using `guzzle/guzzle` instead of `guzzlehttp/guzzle`.

Are you interested in a PR to update this? I'd be happy to contribute.

**Comment by dusterio** [comment]
@djfurman as far as I can see, its alreayd guzzlehttp repo in the composer json?
