### ISSUE TITLE
Permission management

### ISSUE THREAD

**Issue by pedrosoares** [PoweredLocal/vrata#16]
How do i do the permission management on vrata?
I have an API, using lumen by the way, thats have a complexe auth system, in there i can filter witch controler my user has access, but i want to transform that into a microservice, how i going to do that on vrata? If my auth stays on the vrata how my endpoint is going to know who is requesting? and how my endpoint its goind to know the user information? I don't want to duplicate code here, and i want to add later another api made of C++ to interact with. I don't know if i was clear enough.

**Comment by haghft** [comment]
@pedrosoares 
You must change first your APP_ENV  from local to another then if your microservice information in route.json or GATEWAY_ROUTES has not public key , the auth middleware protect your service route automatically.
Note: Dont set auth middleware in your microservice routes!

**Comment by dusterio** [comment]
@pedrosoares "vrata" is adding X-User/X-Token-Scopes HTTP headers to all requests made to microservices so they always know 1) the request passed the authentication 2) who made the request
