### ISSUE TITLE
Support PostgreSQL driver

### ISSUE THREAD

**Issue by witschko** [PoweredLocal/vrata#22]
Hi!

I just recognized (after some hours) that there is no PostgreSQL driver shipped with the Docker image. Since we use PostgreSQL as our user database and Lumen supports it from scratch it would be nice if the driver would come pre-installed with the Docker image.

Best,
Philipp

**Comment by dusterio** [comment]
Sure, can you edit the Dockerfile and make a pull request maybe? :)

**Comment by witschko** [comment]
Ok...that's cool...see #23
