### ISSUE TITLE
No .env.example file in project

### ISSUE THREAD

**Issue by ag2vit** [PoweredLocal/vrata#28]
Installing poweredlocal/vrata (0.2.0)
  - Installing poweredlocal/vrata (0.2.0): Loading from cache
Created project in vrata/
> php -r "copy('.env.example', '.env');"
PHP Warning:  copy(.env.example): failed to open stream: No such file or directory in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. copy() Command line code:1

**Comment by dusterio** [comment]
added
