### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by parthibd** [PoweredLocal/vrata#29]
Has this project been abandoned?

**Comment by ahmed-alaa** [comment]
Looks like that :(

**Comment by dusterio** [comment]
Nope, it's not :) I have a lot of other work/projects, but 'vrata' is definitely open to contributions and suggestions. Also, it's actively used in production on daily basis

**Comment by head1328** [comment]
Sounds good. Is it too much work to fix Travis CI?

`PHP Notice:  Undefined index: CODECLIMATE_REPO_TOKEN in /home/travis/build/PoweredLocal/vrata/vendor/codeclimate/php-test-reporter/src/TestReporter/Entity/JsonFile.php on line 40`

**Comment by dusterio** [comment]
@head1328 where do you get this error?

**Comment by head1328** [comment]
> @head1328 where do you get this error?

look at the 2 pr's

**Comment by dusterio** [comment]
@head1328 yea I think I found it, its because this env variable is present in my Travis CI setup but not in yours - since you created a fork under your own account. Anyway, added a condition in the script section - it should fix this
