### ISSUE TITLE
Docker image should have tag

### ISSUE THREAD

**Issue by peter279k** [PoweredLocal/vrata#32]
As title, it's good to see that this repository has the Docker image and it's available on [Docker hub page](https://hub.docker.com/r/pwred/vrata).

I think we need to tag the version and it can let developers know which versions are stable.

And nobody want to use the unstable version to build Docker container on the production.

**Comment by dusterio** [comment]
@peter279k yep you are right and we thought about this already

we will add Docker image tags shortly

**Comment by peter279k** [comment]
Thanks for reply, @dusterio.

Hopefully you concern about this issue and let Docker image be stable tag version.
